services:
  filters-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    env_file:
      - ./backend/.env.production
    depends_on:
      - filters-db

  filters-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.production
    volumes:
      - filters-postgres_data:/var/lib/postgresql/data

  filters-frontend:
    # image: ${FRONTEND_IMAGE}
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'

    volumes:
      - frontend-node-modules:/app/node_modules
    restart: always
    depends_on:
      - filters-backend
  nginx:
    build:
      context: ./.nginx/
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - filters-frontend

volumes:
  filters-postgres_data:
  frontend-node-modules:
